export const HV_DBR_DEFAULTS = {
  // ─── DOCUMENT INFORMATION ──────────────────────────────────────────────────
  reportTitle: 'Design Basis Report (DBR)',
  projectTitle: '100MW AC Solar Power Plant',
  substationTitle: '69/34.5 kV Kitt Solar HV Collector Substation',
  documentNo: 'PVI-HVD-001',
  revision: 'A',
  preparedDate: new Date().toLocaleDateString("en-GB"),
  preparedByCompany: 'PVinsight Inc',
  preparedByAddress: '5717 Legacy Dr Suite 250, Plano, Texas, 75024',
  submittedToCompany: 'RES',
  submittedToAddress: '456 Renewable Dr, Denver, CO 80202',

  // ─── REVISION HISTORY ───────────────────────────────────────────────────────
  revisions: [
    {
      revision: 'A',
      issueDate: new Date().toLocaleDateString("en-GB").replaceAll("/", "."),
      documentNumber: 'PVI-HVD-001',
      documentName: 'Design Basis Report (DBR)',
      description: 'Preliminary Design'
    }
  ],
  rev0Number: 'A',
  rev0Date: new Date().toLocaleDateString("en-GB").replaceAll("/", "."),
  rev0Description: 'Preliminary Design',
  rev1Number: '1',
  rev1Date: '2026-03-22',
  rev1Description: 'Issued for Approval',
  rev2Number: '2',
  rev2Date: '2026-07-07',
  rev2Description: 'Issued for Construction (IFC)',

  // ─── PROJECT / SITE DETAILS ─────────────────────────────────────────────────
  projectName: 'Kitt Solar',
  state: 'CA',
  county: 'Kern',
  coordinates: '35.1234° N, 118.5678° W',
  poiVoltage: '69',
  mvVoltage: '34.5',
  fenceArea: '2.5',
  acCapacityMW: '100',
  meanExtremeHighTemp: '42',
  avgAnnualTemp: '18',
  extremeHighTemp: '45',
  extremeLowTemp: '-5',
  altitude: '2500',
  designWindSpeed: '110',
  riskCategory: 'Risk Category II',
  designSnowLoad: '10',
  voltageClass: '69/34.5 kV',
  bilRating: '350/200 kV',
  continuousCurrentRating: '3000/3000 A',
  faultLevel69kV: '40',
  faultLevel34_5kV: '31.5',
  systemFrequency: '60',
  skinEffectCoefficient: '1',
  emissivityCoefficient: '0.5',
  conductorConductivityPercent: '53',
  groundFlashDensity: '4',
  conductorIrregularityFactor: '0.85',
  empiricalConstantEo: '21.1',
  windConductorAngle: '90',
  altitudeCorrectionFactor: '1',

  // ─── PROJECT ELECTRICAL SCHEME ──────────────────────────────────────────────
  busbarScheme: 'Single Busbar Scheme',
  numOfHvBreakers: '1',
  numOfMvBreakers: '5',
  backupPowerSource: 'Backup generator or local utility via ATS',

  // ─── CLEARANCES ─────────────────────────────────────────────────────────────
  hvPhaseToPhase: "MIN 5'-0\"",
  hvMetalToMetal: "MIN. 2'-7\"",
  hvPhaseToGround: "MIN. 2'-5\"",
  hvVerticalClearance: "11'-0\"",
  hvHorizontalClearance: "4'-11\"",
  hvFenceClearance: "11'-7\"",
  mvPhaseToPhase: "MIN. 3'-0\"",
  mvMetalToMetal: "MIN. 1'-6\"",
  mvPhaseToGround: "MIN. 1'-3\"",
  mvVerticalClearance: "10'-0\"",
  mvHorizontalClearance: "4'-0\"",
  mvFenceClearance: "10'-7\"",

  // ─── FAULT LEVELS ───────────────────────────────────────────────────────────
  faultLevel69kVRemarks: 'Utility Fault Level Assumed',
  faultLevel34_5kVRemarks: '34.5 kV fault level calculated per MPT size and plant AC capacity',
  mptSizeForFaultCalc: '120 MVA',

  // ─── MAJOR EQUIPMENT (BOM) ──────────────────────────────────────────────────
  majorApparatusTable: `<table class="doc-table"><thead><tr><th style="width: 8%;">S.No</th><th style="width: 25%;">Equipment</th><th style="width: 32%;">Description</th><th style="width: 25%;">Manufacturer</th><th style="width: 10%;">Qty</th></tr></thead><tbody><tr><td>1</td><td>Main Power Transformer</td><td>120/160/200 MVA, 69/34.5 kV, 3-Phase, 60 Hz</td><td>Hitachi Energy</td><td>1</td></tr><tr><td>2</td><td>69 kV Circuit Breaker</td><td>69 kV, 3000 A, 40 kA, SF6 Gas insulated</td><td>Siemens</td><td>1</td></tr><tr><td>3</td><td>34.5 kV Vacuum Circuit Breaker</td><td>38 kV, 3000 A, 31.5 kA, Outdoor vacuum type</td><td>Eaton</td><td>5</td></tr></tbody></table>`,
  bomNote: 'Bill of Material listed is for long lead items only and applicable only for the scope listed.',

  // ─── CONDUCTORS, BUS & INSULATORS ───────────────────────────────────────────
  hvJumperConductor: '(2) 1590 KCMIL AAC COREOPSIS',
  mainBusJumperConductor: '(3) 1590 KCMIL AAC COREOPSIS',
  mvMainBusJumperConductor: '(3) 1590 KCMIL AAC COREOPSIS',
  feederBreakerJumperConductor: '(2) 795 KCMIL AAC LILAC',
  feederJumperConductor: '(1) 795 KCMIL AAC LILAC',
  sstVtJumperConductor: '(1) 4/0 AAC OXLIP',
  dampingConductor5in: '(1) 795 KCMIL AAC ARBUTUS',
  dampingConductor2_5in: '(1) 266.8 KCMIL AAC LAUREL',
  hvBusPipeSize: '5" SCH 40, 6063-T6',
  mvMainBusPipeSize: '5" SCH 40, 6063-T6',
  mvFeederBusPipeSize: '2.5" SCH 40, 6063-T6',
  dampingCable5inTube: '(1) 795 KCMIL AAC ARBUTUS',
  dampingCable2_5inTube: '(1) 266.8 KCMIL AAC LAUREL',
  hvPostInsulator: 'TR-216',
  mvPostInsulator: 'TR-210',
  insulatorContaminationLevel: 'Light',
  insulatorMaxCantileverPercent: '95%',

  // ─── SUBSTATION DESIGN DETAILS ──────────────────────────────────────────────
  controlEnclosureSize: "40' x 14'",
  busExpansionJointSpanLimit: '40 feet',
  groundGridConductor: 'Bare #4/0 soft drawn copper',
  groundRodSpec: '3/4" diameter, 8 feet length, Copper Clad Steel',
  groundGridResistanceLimit: '< 1 Ohm',
  groundingSoftware: 'WinIGS',
  groundingStandard: 'IEEE Std. 80-2013',
  groundingSafetyMarginPercent: '20',
  surfaceLayerDepth: '4-6 inches',
  surfaceRockResistivity: '3000 ohm-meter',
  groundGridExtension: '3 feet',
  illuminationSoftware: 'Visual 2020 Professional',
  illumGeneralExteriorFc: '2',
  illumRemoteAreasFc: '0.5',
  illumControlBuildingDoorsFc: '5',
  lightningStandard: 'IEEE 998',
  rollingSphereStationRadius: '100',
  rollingSphereControlRadius: '125',

  // ─── PROTECTION & CONTROL ───────────────────────────────────────────────────
  sstRatingKva: '100',
  sstPhaseConfig: 'Single Phase',
  atsDistributionVoltage: '120/240VAC Single-Phase',
  fuseSizingPercent: '300',
  dcSystemVoltage: '125',
  batteryRechargeHours: '12',
  batteryLoadCycleHours: '8',
  numOutgoingHvLines: '1',
  hvBreakerTag: '52-T1',
  numMvFeederBreakers: '5',
  numIncomingFeeders: '9',
  linePrimaryRelayModel: 'SEL-311L',
  linePrimaryRelayPartNo: '',
  lineBackupRelayModel: 'SEL-411L',
  hvBreakerRelayModel: 'SEL-351S',
  hvBreakerRelayPartNo: '',
  hvBreakerTagFull: '52-T12',
  transformerMainRelayModel: 'SEL-487E',
  transformerMainRelayPartNo: '',
  transformerBackupRelayModel: 'SEL-787',
  transformerBackupRelayPartNo: '',
  busRelayModel: 'SEL-587Z',
  busRelayPartNo: '',
  feederRelayModel: 'SEL-351S',
  feederRelayPartNo: '',
  meterModel1: 'SEL-735',
  meterModel1PartNo: '',
  meterModel2: 'ION 8650',
  terminalBlockModel: 'GE type EB25B12 600V 30A',
  ctShortingBlockModel: 'GE type EB27B04S',
  panelListText: 'Panel 1: Communications & SCADA; Panel 2: 69kV Line Protection; Panel 3: Transformer Main Protection; Panel 4: 34.5kV Bus Differential & Feeders',
  scadaMasterController: 'Master PPC',
  scadaSubstationController: 'SEL RTAC',
  relayEventDataDestination: 'Dallas',

  // ─── ELECTRICAL CALCULATIONS ────────────────────────────────────────────────
  necEditionForAcLoad: '2020',
  lightsOnPercent: '10',
  heatersOnPercent: '90',
  atsRatingA: '600A',
  batteryNominalVoltage: '125',
  batteryMaxSystemVoltage: '140',
  batteryMinSystemVoltage: '105',
  batteryNumCells: '60',
  batteryMinCellVoltage: '1.75',
  batteryLowestElectrolyteTemp: '50',
  batteryTempCorrectionFactor: '1.19',
  batteryDesignMargin: '1.1',
  batteryAgingFactor: '1.25',
  chargerRechargeTimeHr: '12',
  chargerEfficiency: '1.25',
  chargerAltitudeCorrectionFactor: '1',
  chargerTempCorrectionFactor: '1.19',
  chargerEqualizeVoltage: '2.33',
  chargerFloatVoltage: '2.25',
  hvBusRequiredContinuousA: '1200',
  hvBusSelectedContinuousA: '3000',
  hvBusRequiredScA: '40',
  hvBusSelectedScA: '50',
  mvBusRequiredContinuousA: '2000',
  mvBusSelectedContinuousA: '3000',
  mvBusRequiredScA: '31.5',
  mvBusSelectedScA: '40',
  mvEquipBusRequiredContinuousA: '1200',
  mvEquipBusSelectedContinuousA: '2000',
  mvEquipBusRequiredScA: '31.5',
  mvEquipBusSelectedScA: '40',
  maxBusDeflectionIn: '1',
  hvJumperRequiredA: '1200',
  hvJumper125PctFlaA: '1500',
  hvJumperSelectedA: '2200',
  hvJumperMvaBase: '120',
  mvMainBusJumperRequiredA: '2000',
  mvMainBusJumper125PctFlaA: '2500',
  mvMainBusJumperSelectedA: '3300',
  mvFeederJumperRequiredA: '600',
  mvFeederJumper125PctFlaA: '750',
  mvFeederJumperSelectedA: '1100',
  mvFeederJumperMvaBase: '30',

  // ─── DOCUMENTATION & STUDIES ────────────────────────────────────────────────
  mdlListName: 'Kitt Solar MDL list',
  studiesList: 'Short Circuit Analysis; Reactive Power Study; Insulation Coordination Study; Grounding Study Report; Protection Coordination and Relay Settings Study; Ampacity Study; Substation Illumination Study; Substation Lightning Protection'
};
