"""Initial migration

Revision ID: abd1b569badc
Revises: 
Create Date: 2026-08-10 19:19:37.011281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd1b569badc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('pv_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('module_model', sa.String(), nullable=True),
    sa.Column('bifacial_coefficient', sa.String(), nullable=True),
    sa.Column('temperature_coefficients', sa.JSON(), nullable=True),
    sa.Column('noct', sa.String(), nullable=True),
    sa.Column('series_fuse_rating', sa.String(), nullable=True),
    sa.Column('operating_temperature_range', sa.String(), nullable=True),
    sa.Column('dimensions_mm', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.String(), nullable=True),
    sa.Column('cells_count', sa.String(), nullable=True),
    sa.Column('cell_type', sa.String(), nullable=True),
    sa.Column('front_glass', sa.String(), nullable=True),
    sa.Column('back_glass', sa.String(), nullable=True),
    sa.Column('output_cable', sa.String(), nullable=True),
    sa.Column('connector', sa.String(), nullable=True),
    sa.Column('junction_box', sa.String(), nullable=True),
    sa.Column('load_rating', sa.JSON(), nullable=True),
    sa.Column('degradation', sa.JSON(), nullable=True),
    sa.Column('warranty', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pv_modules_id'), 'pv_modules', ['id'], unique=False)
    op.create_index(op.f('ix_pv_modules_manufacturer'), 'pv_modules', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_pv_modules_module_model'), 'pv_modules', ['module_model'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('pv_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('pmax', sa.String(), nullable=True),
    sa.Column('pstc', sa.String(), nullable=True),
    sa.Column('voc', sa.String(), nullable=True),
    sa.Column('vmp', sa.String(), nullable=True),
    sa.Column('isc', sa.String(), nullable=True),
    sa.Column('imp', sa.String(), nullable=True),
    sa.Column('efficiency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['pv_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pv_variants_id'), 'pv_variants', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('document_no', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('prepared_date', sa.String(), nullable=True),
    sa.Column('report_title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('battery_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('battery_manufacturer', sa.String(), nullable=True),
    sa.Column('battery_model', sa.String(), nullable=True),
    sa.Column('cell_chemistry', sa.String(), nullable=True),
    sa.Column('charge_characteristics', sa.JSON(), nullable=True),
    sa.Column('discharge_characteristics', sa.JSON(), nullable=True),
    sa.Column('thermal_limits', sa.JSON(), nullable=True),
    sa.Column('protection_settings', sa.JSON(), nullable=True),
    sa.Column('cycle_life', sa.Integer(), nullable=True),
    sa.Column('operating_conditions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_battery_reports_id'), 'battery_reports', ['id'], unique=False)
    op.create_table('cable_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('conductor_material', sa.String(), nullable=True),
    sa.Column('insulation_type', sa.String(), nullable=True),
    sa.Column('voltage_rating', sa.String(), nullable=True),
    sa.Column('cable_size', sa.String(), nullable=True),
    sa.Column('no_of_runs', sa.Integer(), nullable=True),
    sa.Column('installation_method', sa.String(), nullable=True),
    sa.Column('soil_thermal_resistivity', sa.Float(), nullable=True),
    sa.Column('soil_temperature', sa.Float(), nullable=True),
    sa.Column('load_factor', sa.Float(), nullable=True),
    sa.Column('derated_ampacity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_cable_reports_id'), 'cable_reports', ['id'], unique=False)
    op.create_table('electrical_design_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('system_frequency_hz', sa.Float(), nullable=True),
    sa.Column('short_circuit_level_ka', sa.Float(), nullable=True),
    sa.Column('max_voltage_drop_percent', sa.Float(), nullable=True),
    sa.Column('grounding_system_type', sa.String(), nullable=True),
    sa.Column('design_standards', sa.JSON(), nullable=True),
    sa.Column('key_design_parameters', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_electrical_design_reports_id'), 'electrical_design_reports', ['id'], unique=False)
    op.create_table('grounding_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('grounding_software', sa.String(), nullable=True),
    sa.Column('ground_conductor_bess', sa.String(), nullable=True),
    sa.Column('ground_conductor_pcs', sa.String(), nullable=True),
    sa.Column('ground_conductor_aux', sa.String(), nullable=True),
    sa.Column('ground_conductor_misc', sa.String(), nullable=True),
    sa.Column('grounding_layout_drawing_no', sa.String(), nullable=True),
    sa.Column('grounding_analysis_report_no', sa.String(), nullable=True),
    sa.Column('safety_body_weight_kg', sa.Float(), nullable=True),
    sa.Column('safety_shock_duration_sec', sa.Float(), nullable=True),
    sa.Column('soil_resistivity_model', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_grounding_reports_id'), 'grounding_reports', ['id'], unique=False)
    op.create_table('inverter_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('inverter_manufacturer', sa.String(), nullable=True),
    sa.Column('inverter_model', sa.String(), nullable=True),
    sa.Column('voltage_limits', sa.JSON(), nullable=True),
    sa.Column('current_limits', sa.JSON(), nullable=True),
    sa.Column('mppt_details', sa.JSON(), nullable=True),
    sa.Column('ac_specifications', sa.JSON(), nullable=True),
    sa.Column('dc_specifications', sa.JSON(), nullable=True),
    sa.Column('efficiency_curves', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_inverter_reports_id'), 'inverter_reports', ['id'], unique=False)
    op.create_table('pcs_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('pcs_manufacturer', sa.String(), nullable=True),
    sa.Column('pcs_model', sa.String(), nullable=True),
    sa.Column('voltage_limits', sa.JSON(), nullable=True),
    sa.Column('current_limits', sa.JSON(), nullable=True),
    sa.Column('mppt_details', sa.JSON(), nullable=True),
    sa.Column('ac_specifications', sa.JSON(), nullable=True),
    sa.Column('dc_specifications', sa.JSON(), nullable=True),
    sa.Column('efficiency_curves', sa.JSON(), nullable=True),
    sa.Column('communication_interfaces', sa.JSON(), nullable=True),
    sa.Column('protection_features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_pcs_reports_id'), 'pcs_reports', ['id'], unique=False)
    op.create_table('pv_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('module_manufacturer', sa.String(), nullable=True),
    sa.Column('module_model', sa.String(), nullable=True),
    sa.Column('electrical_characteristics', sa.JSON(), nullable=True),
    sa.Column('mechanical_characteristics', sa.JSON(), nullable=True),
    sa.Column('temperature_coefficients', sa.JSON(), nullable=True),
    sa.Column('string_sizing', sa.JSON(), nullable=True),
    sa.Column('pvsyst_results', sa.JSON(), nullable=True),
    sa.Column('irradiation_data', sa.JSON(), nullable=True),
    sa.Column('energy_yield', sa.JSON(), nullable=True),
    sa.Column('loss_analysis', sa.JSON(), nullable=True),
    sa.Column('voc_calculations', sa.JSON(), nullable=True),
    sa.Column('isc_calculations', sa.JSON(), nullable=True),
    sa.Column('degradation_tables', sa.JSON(), nullable=True),
    sa.Column('site_conditions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_pv_reports_id'), 'pv_reports', ['id'], unique=False)
    op.create_table('relay_protection_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('relay_manufacturer', sa.String(), nullable=True),
    sa.Column('relay_model', sa.String(), nullable=True),
    sa.Column('ansi_codes', sa.String(), nullable=True),
    sa.Column('ct_ratio', sa.String(), nullable=True),
    sa.Column('pt_ratio', sa.String(), nullable=True),
    sa.Column('pickup_settings', sa.JSON(), nullable=True),
    sa.Column('delay_settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_relay_protection_reports_id'), 'relay_protection_reports', ['id'], unique=False)
    op.create_table('structural_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('wind_load_mph', sa.Float(), nullable=True),
    sa.Column('snow_load_psf', sa.Float(), nullable=True),
    sa.Column('seismic_design_category', sa.String(), nullable=True),
    sa.Column('foundation_type', sa.String(), nullable=True),
    sa.Column('soil_bearing_capacity', sa.String(), nullable=True),
    sa.Column('structural_steel_grade', sa.String(), nullable=True),
    sa.Column('concrete_strength_psi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_structural_reports_id'), 'structural_reports', ['id'], unique=False)
    op.create_table('switchgear_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('switchgear_manufacturer', sa.String(), nullable=True),
    sa.Column('switchgear_model', sa.String(), nullable=True),
    sa.Column('rated_voltage_kv', sa.Float(), nullable=True),
    sa.Column('rated_current_a', sa.Float(), nullable=True),
    sa.Column('short_circuit_withstand_ka', sa.Float(), nullable=True),
    sa.Column('busbar_material', sa.String(), nullable=True),
    sa.Column('ip_rating', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_switchgear_reports_id'), 'switchgear_reports', ['id'], unique=False)
    op.create_table('transformer_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('transformer_manufacturer', sa.String(), nullable=True),
    sa.Column('transformer_model', sa.String(), nullable=True),
    sa.Column('capacity_kva', sa.Float(), nullable=True),
    sa.Column('voltage_ratio', sa.String(), nullable=True),
    sa.Column('impedance_percent', sa.Float(), nullable=True),
    sa.Column('cooling_class', sa.String(), nullable=True),
    sa.Column('losses_no_load_w', sa.Float(), nullable=True),
    sa.Column('losses_load_w', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_transformer_reports_id'), 'transformer_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformer_reports_id'), table_name='transformer_reports')
    op.drop_table('transformer_reports')
    op.drop_index(op.f('ix_switchgear_reports_id'), table_name='switchgear_reports')
    op.drop_table('switchgear_reports')
    op.drop_index(op.f('ix_structural_reports_id'), table_name='structural_reports')
    op.drop_table('structural_reports')
    op.drop_index(op.f('ix_relay_protection_reports_id'), table_name='relay_protection_reports')
    op.drop_table('relay_protection_reports')
    op.drop_index(op.f('ix_pv_reports_id'), table_name='pv_reports')
    op.drop_table('pv_reports')
    op.drop_index(op.f('ix_pcs_reports_id'), table_name='pcs_reports')
    op.drop_table('pcs_reports')
    op.drop_index(op.f('ix_inverter_reports_id'), table_name='inverter_reports')
    op.drop_table('inverter_reports')
    op.drop_index(op.f('ix_grounding_reports_id'), table_name='grounding_reports')
    op.drop_table('grounding_reports')
    op.drop_index(op.f('ix_electrical_design_reports_id'), table_name='electrical_design_reports')
    op.drop_table('electrical_design_reports')
    op.drop_index(op.f('ix_cable_reports_id'), table_name='cable_reports')
    op.drop_table('cable_reports')
    op.drop_index(op.f('ix_battery_reports_id'), table_name='battery_reports')
    op.drop_table('battery_reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_pv_variants_id'), table_name='pv_variants')
    op.drop_table('pv_variants')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_pv_modules_module_model'), table_name='pv_modules')
    op.drop_index(op.f('ix_pv_modules_manufacturer'), table_name='pv_modules')
    op.drop_index(op.f('ix_pv_modules_id'), table_name='pv_modules')
    op.drop_table('pv_modules')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
